version: '2'
services:
  app:
    restart: always
    image: ${DOCKER_REPO_NAME}:${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}
    expose:
      - 80
    env_file:
      - .env
    environment:
      - APACHE_LOG_DIR=/var/www/logs
      - VIRTUAL_HOST=neunerlei.eu,www.neunerlei.eu
      - CERT_NAME=neunerlei.eu
    volumes:
      - ${APP_LOG_DIR}:/var/www/logs
    networks:
      - web_net

networks:
  web_net:
    external: true